services:
  tests:
    image: golang:1.24
    working_dir: /go/src/app
    restart: "no"  # Важно для корректного кода возврата
    volumes:
      - ../:/go/src/app:ro
    environment:
      INTEGRATION_APP_ADDR: "http://app:8888"
      INTEGRATION_PG_DSN: ${INTEGRATION_PG_DSN:-postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable}
    networks:
      - deployments_calendar_network
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "echo 'Waiting for services...'; for i in `seq 1 30`; do curl -sSf http://app:8888/ >/dev/null && break || sleep 1; done; echo 'Running tests'; cd /go/src/app; go test ./tests/integration -v; exit $?",
      ]

networks:
  deployments_calendar_network:
    external: true