apiVersion: v1
kind: Secret
metadata:
  name: calendar-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword }}
  RABBIT_USER: {{ .Values.secret.rabbitUser }}
  RABBIT_PASSWORD: {{ .Values.secret.rabbitPassword }}
